import {
   InputText,
   InputNumber,
   Select,
   SelectButton,
   AutoComplete,
   CascadeSelect,
   Checkbox,
   DatePicker,
   FloatLabel,
   IconField,
   InputMask,
   MultiSelect,
   Rating,
   Textarea,
   ToggleButton,
} from "primevue";
import CustomUpload from "@/components/ui/CustomUpload.vue";

export const PrimeVueInputs = {
   InputText,
   InputNumber,
   Select,
   SelectButton,
   AutoComplete,
   CascadeSelect,
   Checkbox,
   DatePicker,
   FloatLabel,
   IconField,
   InputMask,
   MultiSelect,
   Rating,
   Textarea,
   ToggleButton,
   CustomUpload,
};
