#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);



// Kafelarni uslugalarni elonlari poka vipga
// Click naxt
// Rasmlarni korishni yaxwilash kerak.
// Podelitsa qoshish
// Telegramdagi til orqali usha tilda ochilish`

// Correct price sort dollar | sum +
// Ads forceDelete +

// Shop akkaunt
// Notification fallowing ads
// Admin Panel
// Statistika